#!/bin/bash

cat ./zprofile_source >> ~/.zprofile

brew install stats
brew install ffmpeg

machineName=yeoman
sudo scutil --set ComputerName $machineName
sudo scutil --set LocalHostName $machineName
sudo scutil --set HostName $machineName